# Generated by Django 2.1.4 on 2019-01-16 14:37

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutlist',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
