# Generated by Django 2.1.4 on 2019-01-20 08:09

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20190116_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='WorksList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', markdownx.models.MarkdownxField(blank=True)),
                ('created', models.DateField(default='2019-01-20')),
                ('image', stdimage.models.StdImageField(blank=True, upload_to='path/to/img')),
                ('category', models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to='myblog.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='aboutlist',
            name='created',
            field=models.DateField(default='2019-01-20'),
        ),
    ]
