# Generated by Django 2.1.4 on 2019-01-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20190120_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateField(default='2019-01-20'),
        ),
    ]
