# Generated by Django 2.1.4 on 2019-01-21 09:18

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_category_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='workslist',
            name='link1',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AddField(
            model_name='workslist',
            name='link2',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AddField(
            model_name='workslist',
            name='link3',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutlist',
            name='created',
            field=models.DateField(default='2019-01-21'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateField(default='2019-01-21'),
        ),
        migrations.AlterField(
            model_name='workslist',
            name='created',
            field=models.DateField(default='2019-01-21'),
        ),
    ]
