# Generated by Django 2.1.4 on 2019-01-21 09:24

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_auto_20190121_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workslist',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='path/works'),
        ),
    ]
