# Generated by Django 2.1.4 on 2019-01-21 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_auto_20190121_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workslist',
            old_name='link1',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='workslist',
            name='link2',
        ),
        migrations.RemoveField(
            model_name='workslist',
            name='link3',
        ),
    ]
